# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-20 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0037_auto_20180108_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertag',
            name='alert',
            field=models.CharField(blank=True, help_text='An alert to show to users who have this usertag.', max_length=164),
        ),
    ]
