# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-09 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0038_auto_20180212_1556'),
        ('course', '0038_auto_20180326_1425'),
    ]

    operations = [
    ]
